### ISSUE TITLE
upload to maven central

### ISSUE THREAD

**Issue by sreich** [SudoPlayGames/Joise#5]
Could we upload to maven central so it's easy to add to a project, so i can just do in my gradle dependencies { compile "com.blah..".. }

I'm not very familiar with gradle, maven, or maven central, perhaps you are though :)

**Comment by codetaylor** [comment]
I think that's a good idea. I'm not very familiar with maven, but I will look into it.

**Comment by codetaylor** [comment]
I'm just waiting for the repos to be created. As soon as that's done I'll deploy it to maven and we can see if it works! :)

**Comment by codetaylor** [comment]
You should be able to get the jars from Maven now:

```
groupId=com.sudoplay.joise
artifactId=joise
version=1.0.1
```

Let me know if it works or if you have any problems!

**Comment by BenMcLean** [comment]
Could you update maven central to your latest 1.0.2 please?

**Comment by codetaylor** [comment]
Sure thing - I should be able to get it done tomorrow. 

Reference: #9
