### ISSUE TITLE
generating infinite terrain

### ISSUE THREAD

**Issue by alwex** [SudoPlayGames/Joise#6]
Hello, I am not sure if this is the right place to ask, but I found your library just amazing and I would like to tell you about.

I am facing a problem while using the library, I have made a few test with the different modules, and my comprehension is that I must now the final dimensions of my map before generating it. Let me explain:

the `get` function of the modules look this way

    get(x, y) // x and t are value between 0 and 1

so I need to call

    get(x / map_witdh, y / map_heigh)

in order to obtain the point value.

I would like to use it in an inifinite map, so that if the player is at coord (1000, 400), I just need to generate the surrounding blocks etc...

Is there a way to achieve that? I am quite sure I have missed something. A documentation or a wiki would be very helpful.

Thank you

**Comment by codetaylor** [comment]
Hi alwex,

You're in the right place, and correct: this project could benefit from some documentation or a wiki with some answers to common questions. I will pencil this into my schedule. :)

In the meantime...

```java

// let's say you're generating in chunks and chunk position (0,0), (0,1), (1,-1), etc.. (X,Y)
float[] generate(int chunkPositionX, int chunkPositionY) {
	
	// mess with this to get the scale you want
	float noiseScale = 1.0f / 256.0f;

	// chunks are 16x16 tiles
	int chunkSize = 16;

	// convert chunkPositionX and chunkPositionY to a tile offset
	float offsetX = chunkPositionX * chunkSize;
	float offsetY = chunkPositionY * chunkSize;

	// set up the array to hold the noise samples
	float[] result = new float[256];

	// loop and sample the noise
	float sampleX, sampleY;
	for (int x = 0; x < chunkSize; ++x) {
		for (int y = 0; y < chunkSize; ++y) {
			float sampleX = (x + offsetX) * noiseScale;
			float sampleY = (y + offsetY) * noiseScale;
			result[x + (y * chunkSize)] = joise.get(sampleX, sampleY);
		}
	}

	return result;
}
```

Hope this helps!

**Comment by codetaylor** [comment]
Here is a simpler method if you're not using chunks:

```java
float[] generate(int playerX, int playerY) {
	float noiseScale = 1.0f / 256.0f;
	float sampleX = playerX * noiseScale;
	float sampleY = playerY * noiseScale;
	return joise.get(sampleX, sampleY);
}
```

The sample coordinates used in the get() method don't have to be between 0 and 1, they just have to be floats.

**Comment by alwex** [comment]
Hi Jason,

Thank you very much the examples. I plan to use chunck (If I want my world
to be infinite, I may prevent memory usage and discharge the chunk on the
drive when the player is not there). Do you have some advices to create
this kind of engine ? I am also wondering how to determinate where to place
the differents biomes.

Thank you by the way

2015-09-26 17:15 GMT+02:00 Jason Taylor <notifications@github.com>:
